BASE_TASK_CONFIG_PATH: "config/hwnav_base.yaml"
NUM_PROCESSES: 1
SENSORS: ["DEPTH_SENSOR"]
TEST_EPISODE_COUNT: 500
VIDEO_OPTION: []
VISUALIZATION_OPTION: []

EVAL:
  SPLIT: "val"
  USE_CKPT_CONFIG: True